CREATE SCHEMA IF NOT EXISTS DELIVERY_SERVICE;

CREATE TABLE DELIVERY_SERVICE.TAB_USER (
  TUS_ID_USER NUMBER(12) NOT NULL,
  TUS_NAME VARCHAR2(20) NOT NULL,
  TUS_MAIL_ADDRESS VARCHAR2(1000) NOT NULL,
  TUS_ADDRESS VARCHAR2(1000) NOT NULL,
  CONSTRAINT PK_USER PRIMARY KEY (TUS_ID_USER)
);

CREATE UNIQUE INDEX DELIVERY_SERVICE.PK_TAB_USER ON DELIVERY_SERVICE.TAB_USER (TUS_ID_USER);

CREATE SEQUENCE DELIVERY_SERVICE.SEQ_USER MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1;

CREATE TABLE DELIVERY_SERVICE.TAB_PRODUCT (
  TPD_ID_PRODUCT NUMBER(12) NOT NULL,
  TPD_NAME VARCHAR2(20) NOT NULL,
  TPD_DETAILS VARCHAR2(1000) NOT NULL,
  TPD_PRICE NUMBER(40) NOT NULL,
  CONSTRAINT PK_PRODUCT PRIMARY KEY (TPD_ID_PRODUCT)
);

CREATE UNIQUE INDEX DELIVERY_SERVICE.PK_TAB_PRODUCT ON DELIVERY_SERVICE.TAB_PRODUCT (TPD_ID_PRODUCT);

CREATE SEQUENCE DELIVERY_SERVICE.SEQ_PRODUCT MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1;

CREATE TABLE DELIVERY_SERVICE.TAB_CART (
  TCA_ID_CART NUMBER(12) NOT NULL,
  TCA_TUS_ID_USER NUMBER(12) NOT NULL,
  CONSTRAINT PK_CART PRIMARY KEY (TCA_ID_CART)
);

CREATE UNIQUE INDEX DELIVERY_SERVICE.PK_TAB_CART ON DELIVERY_SERVICE.TAB_CART (TCA_ID_CART);

CREATE SEQUENCE DELIVERY_SERVICE.SEQ_CART MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1;

CREATE TABLE DELIVERY_SERVICE.TAB_ORDER (
  TOR_ID_ORDER NUMBER(12) NOT NULL,
  TOR_TCA_ID_CART NUMBER(12) NOT NULL,
  TOR_TPD_ID_PRODUCT NUMBER(12) NOT NULL,
  CONSTRAINT PK_ORDER PRIMARY KEY (TOR_ID_ORDER)
);

CREATE UNIQUE INDEX DELIVERY_SERVICE.PK_TAB_ORDER ON DELIVERY_SERVICE.TAB_ORDER (TOR_ID_ORDER);

CREATE SEQUENCE DELIVERY_SERVICE.SEQ_ORDER MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1;

CREATE TABLE DELIVERY_SERVICE.TAB_SENDER (
  TSD_ID_SENDER NUMBER(12) NOT NULL,
  TSD_NAME VARCHAR2(200) NOT NULL, 
  CONSTRAINT PK_SENDER PRIMARY KEY (TSD_ID_SENDER)
);
CREATE UNIQUE INDEX DELIVERY_SERVICE.PK_TAB_SENDER ON DELIVERY_SERVICE.TAB_SENDER (TSD_ID_SENDER);

CREATE SEQUENCE DELIVERY_SERVICE.SEQ_SENDER MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1;

CREATE TABLE DELIVERY_SERVICE.TAB_TEMPLATE (
  TTP_ID_TEMPLATE NUMBER(12) NOT NULL,
  TTP_CONTENT CLOB NOT NULL,
  TTP_TYPE NUMBER(1) NOT NULL,
  TTP_NAME VARCHAR2(60) NOT NULL,
  TTP_DESCRIPTION VARCHAR2(240) NOT NULL,
  TTP_STATUS NUMBER(1) NOT NULL,
  CONSTRAINT PK_TEMPLATE PRIMARY KEY (TTP_ID_TEMPLATE)
);
CREATE UNIQUE INDEX DELIVERY_SERVICE.PK_TAB_TEMPLATE ON DELIVERY_SERVICE.TAB_TEMPLATE (TTP_ID_TEMPLATE);

CREATE SEQUENCE DELIVERY_SERVICE.SEQ_TEMPLATE MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1;

CREATE TABLE DELIVERY_SERVICE.TAB_MESSAGE (
  TMS_ID_MESSAGE NUMBER(12) NOT NULL,
  TMS_TSD_ID_SENDER NUMBER(12) NOT NULL,
  TMS_TTP_ID_TEMPLATE NUMBER(12) NOT NULL,
  TMS_DATE TIMESTAMP NOT NULL,
  TMS_SCHEDULE TIMESTAMP NOT NULL,
  TMS_STATUS NUMBER(2) NOT NULL,
  CONSTRAINT PK_MESSAGE PRIMARY KEY (TMS_ID_MESSAGE),
  CONSTRAINT FK_SENDER FOREIGN KEY (TMS_TSD_ID_SENDER)
  REFERENCES DELIVERY_SERVICE.TAB_SENDER(TSD_ID_SENDER),
  CONSTRAINT FK_TEMPLATE FOREIGN KEY (TMS_TTP_ID_TEMPLATE)
  REFERENCES DELIVERY_SERVICE.TAB_TEMPLATE(TTP_ID_TEMPLATE)
);
CREATE UNIQUE INDEX DELIVERY_SERVICE.PK_TAB_MESSAGE ON DELIVERY_SERVICE.TAB_MESSAGE (TMS_ID_MESSAGE);

CREATE SEQUENCE DELIVERY_SERVICE.SEQ_MESSAGE MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1;

CREATE TABLE DELIVERY_SERVICE.TAB_MESSAGE_PARAM (
  TMP_ID NUMBER(12) NOT NULL,
  TMP_TMS_ID_MESSAGE NUMBER(12) NOT NULL,
  TMP_NAME VARCHAR2(30) NOT NULL,
  TMP_VALUE CLOB NOT NULL,
  TMP_AUTHOR VARCHAR2(30),
  CONSTRAINT PK_MESSAGE_PARAM PRIMARY KEY (TMP_ID),
  CONSTRAINT FK_MESSAGE FOREIGN KEY (TMP_TMS_ID_MESSAGE)
  REFERENCES DELIVERY_SERVICE.TAB_MESSAGE(TMS_ID_MESSAGE)
);

CREATE UNIQUE INDEX DELIVERY_SERVICE.PK_TAB_MESSAGE_PARAM ON DELIVERY_SERVICE.TAB_MESSAGE_PARAM (TMP_ID);

CREATE SEQUENCE DELIVERY_SERVICE.SEQ_MESSAGE_PARAM MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1;

CREATE TABLE DELIVERY_SERVICE.TAB_ATTACHMENT (
  TAT_ID_ATTACHMENT NUMBER(12) NOT NULL,
  TAT_TMS_ID_MESSAGE NUMBER(12) NOT NULL,
  TAT_CONTENT BLOB NOT NULL,
  TAT_FILE_NAME VARCHAR2(100) NOT NULL,
  TAT_MIME_TYPE VARCHAR(100) NOT NULL,
  CONSTRAINT PK_ATTACHMENT PRIMARY KEY (TAT_ID_ATTACHMENT),
  CONSTRAINT FK_TAT_MESSAGE FOREIGN KEY (TAT_TMS_ID_MESSAGE)
  REFERENCES DELIVERY_SERVICE.TAB_MESSAGE(TMS_ID_MESSAGE)
);
CREATE UNIQUE INDEX DELIVERY_SERVICE.PK_TAB_ATTACHMENT ON DELIVERY_SERVICE.TAB_ATTACHMENT (TAT_ID_ATTACHMENT);

CREATE SEQUENCE DELIVERY_SERVICE.SEQ_ATTACHMENT MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1;

CREATE TABLE DELIVERY_SERVICE.TAB_DELIVERY_JOB (
  TDJ_ID_DELIVERY_JOB NUMBER(12) NOT NULL,
  TDJ_STATUS NUMBER(2) NOT NULL,
  TDJ_SEND_DATE TIMESTAMP,
  CONSTRAINT PK_DELIVERY_JOB PRIMARY KEY (TDJ_ID_DELIVERY_JOB)
);

CREATE UNIQUE INDEX DELIVERY_SERVICE.PK_TAB_DELIVERY_JOB ON DELIVERY_SERVICE.TAB_DELIVERY_JOB (TDJ_ID_DELIVERY_JOB);

CREATE SEQUENCE DELIVERY_SERVICE.SEQ_DELIVERY_JOB MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1;

CREATE TABLE DELIVERY_SERVICE.TAB_RECIPIENT (
  TRC_ID_RECIPIENT NUMBER(12) NOT NULL,
  TRC_TMS_ID_MESSAGE NUMBER(12) NOT NULL, 
  TRC_TDJ_ID_DELIVERY_JOB NUMBER(12), 
  TRC_ADDRESS VARCHAR2(1000) NOT NULL, 
  TRC_TYPE NUMBER(1) NOT NULL,
  CONSTRAINT PK_RECIPIENT PRIMARY KEY (TRC_ID_RECIPIENT),
  CONSTRAINT FK_TRC_MESSAGE FOREIGN KEY (TRC_TMS_ID_MESSAGE)
  REFERENCES DELIVERY_SERVICE.TAB_MESSAGE(TMS_ID_MESSAGE),
  CONSTRAINT FK_TRC_DELIVERY_JOB FOREIGN KEY (TRC_TDJ_ID_DELIVERY_JOB)
  REFERENCES DELIVERY_SERVICE.TAB_DELIVERY_JOB(TDJ_ID_DELIVERY_JOB)
);
CREATE UNIQUE INDEX DELIVERY_SERVICE.PK_TAB_RECIPIENT ON DELIVERY_SERVICE.TAB_RECIPIENT (TRC_ID_RECIPIENT);

CREATE SEQUENCE DELIVERY_SERVICE.SEQ_RECIPIENT MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1;

CREATE TABLE DELIVERY_SERVICE.TAB_DELIVERY_JOB_LOG (
  TDL_ID NUMBER(12) NOT NULL,
  TDL_TDJ_ID_DELIVERY_JOB NUMBER(12) NOT NULL, 
  TDL_DATE TIMESTAMP,
  TDL_ERROR CLOB NOT NULL, 
  CONSTRAINT PK_DELIVERY_JOB_LOG PRIMARY KEY (TDL_ID),
  CONSTRAINT FK_DELIVERY_JOB FOREIGN KEY (TDL_TDJ_ID_DELIVERY_JOB)
  REFERENCES DELIVERY_SERVICE.TAB_DELIVERY_JOB(TDJ_ID_DELIVERY_JOB)
);
CREATE UNIQUE INDEX DELIVERY_SERVICE.PK_TAB_DELIVERY_JOB_LOG ON DELIVERY_SERVICE.TAB_DELIVERY_JOB_LOG (TDL_ID);

CREATE SEQUENCE DELIVERY_SERVICE.SEQ_DELIVERY_JOB_LOG MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1;

INSERT INTO DELIVERY_SERVICE.TAB_SENDER (TSD_ID_SENDER,TSD_NAME) values (DELIVERY_SERVICE.SEQ_SENDER.NEXTVAL,'delivery');

INSERT INTO DELIVERY_SERVICE.TAB_TEMPLATE (TTP_ID_TEMPLATE, 
  TTP_CONTENT,
  TTP_TYPE,
  TTP_NAME,
  TTP_DESCRIPTION,
  TTP_STATUS) values (DELIVERY_SERVICE.SEQ_TEMPLATE.NEXTVAL,'HTML', 1, 'OrderTemplate','Template de Registro de Pedidos', 1);

INSERT INTO DELIVERY_SERVICE.TAB_TEMPLATE (TTP_ID_TEMPLATE, 
  TTP_CONTENT,
  TTP_TYPE,
  TTP_NAME,
  TTP_DESCRIPTION,
  TTP_STATUS) values (DELIVERY_SERVICE.SEQ_TEMPLATE.NEXTVAL,'HTML', 1, 'SendTemplate','Template de Registro de Envio', 1);

INSERT INTO DELIVERY_SERVICE.TAB_TEMPLATE (TTP_ID_TEMPLATE, 
  TTP_CONTENT,
  TTP_TYPE,
  TTP_NAME,
  TTP_DESCRIPTION,
  TTP_STATUS) values (DELIVERY_SERVICE.SEQ_TEMPLATE.NEXTVAL,'HTML', 1, 'CheckoutTemplate','Template de Finalização de Pedido', 1);  

INSERT INTO DELIVERY_SERVICE.TAB_MESSAGE (TMS_ID_MESSAGE,
  TMS_TSD_ID_SENDER,
  TMS_TTP_ID_TEMPLATE,
  TMS_DATE,
  TMS_SCHEDULE,TMS_STATUS) values (DELIVERY_SERVICE.SEQ_MESSAGE.NEXTVAL,1, 3,'2020-04-06T03:00:00', '2020-04-06T03:00:00', 1);
  
INSERT INTO DELIVERY_SERVICE.TAB_MESSAGE_PARAM (TMP_ID,
  TMP_TMS_ID_MESSAGE,
  TMP_NAME,
  TMP_VALUE,
  TMP_AUTHOR) values (DELIVERY_SERVICE.SEQ_MESSAGE_PARAM.NEXTVAL, 1 , 'Notebook', 'Pedido acima foi Recebido, aguarde a confirmação do pagamento para envio do produto', 'delivery');
  
INSERT INTO DELIVERY_SERVICE.TAB_DELIVERY_JOB (
  TDJ_ID_DELIVERY_JOB,
  TDJ_STATUS,
  TDJ_SEND_DATE) values (DELIVERY_SERVICE.SEQ_DELIVERY_JOB.NEXTVAL, 0 , '2020-04-06T03:00:00');
  
INSERT INTO DELIVERY_SERVICE.TAB_RECIPIENT (
  TRC_ID_RECIPIENT,
  TRC_TMS_ID_MESSAGE, 
  TRC_TDJ_ID_DELIVERY_JOB, 
  TRC_ADDRESS, 
  TRC_TYPE) values (DELIVERY_SERVICE.SEQ_RECIPIENT.NEXTVAL, 1, 1, 'otaviocesarcostasantos@gmail.com',0);  
  
INSERT INTO DELIVERY_SERVICE.TAB_RECIPIENT (
  TRC_ID_RECIPIENT,
  TRC_TMS_ID_MESSAGE, 
  TRC_TDJ_ID_DELIVERY_JOB, 
  TRC_ADDRESS, 
  TRC_TYPE) values (DELIVERY_SERVICE.SEQ_RECIPIENT.NEXTVAL, 1, 1, 'otaviocaesar@gmail.com',1);		